version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - npm run build

artifacts:
  files:
    - build/**/*
    - node_modules/**/*
    - package.json
    - Procfile
    - .env,

cache:
  paths:
    - node_modules/**/*
