name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js version from .nvmrc file
        uses: actions/setup-node@v3
        cache: 'npm'
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Check TypeScript types
        run: npm run check-types

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npx playwright install && npm run test:integration

      - name: Lint
        run: npm run lint
